apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  labels:
    app: kafka
data:
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_RESTART_ATTEMPTS: "10"
  KAFKA_RESTART_DELAY: "5"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
  ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"