spring:
  application:
    name: techchallenge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/techchallenge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    mixed: true
    clean-disabled: false
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true
  messages:
    basename: messages
  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      health:
        show-details: always
        enabled: true
      info:
        enabled: true
      prometheus:
        enabled: true

server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/techchallenge/v1}
  error:
    include-binding-errors: never

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_API_DOCS_PATH:/api-docs}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_UI_PATH:/swagger-ui}

mercado-pago:
  access-token: APP_USR-1131579974414437-053021-157504008fa8e28304d4b2560b3cf474-2466834857
  collector-id: 2466834857
  pos-id: CaixaPOS1
  notification-url: ${NOTIFICATION_URL:https://f0c2-2804-1b3-aa83-b1ee-5de8-e154-a7d9-6180.ngrok-free.app}

logging:
  level:
    root: INFO
    org.springframework: INFO
    br.com.fiap.postech: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
