spring:
  application:
    name: techchallenge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/techchallenge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    basename: messages

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/techchallenge/v1}

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_API_DOCS_PATH:/api-docs}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_UI_PATH:/swagger-ui}