spring:
  application:
    name: techchallenge
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  data:
    mongodb:
      uri: mongodb://mongo:27017/customerdb
  messages:
    basename: messages
  management:
    endpoints:
      web:
        exposure:
          include: health,info,prometheus
    endpoint:
      health:
        show-details: always
        enabled: true
      info:
        enabled: true
      prometheus:
        enabled: true

server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/techchallenge/v1}
  error:
    include-binding-errors: never

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_API_DOCS_PATH:/api-docs}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}
    path: ${SWAGGER_UI_PATH:/swagger-ui}

logging:
  level:
    root: INFO
    org.springframework: INFO
    br.com.fiap.postech: INFO
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
