apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-config
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/techchallenge"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_PROFILES_ACTIVE: "default"