apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-service
  labels:
    app: tech-challenge-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30358
      protocol: TCP
  selector:
    app: tech-challenge-app
  type: LoadBalancer