apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-config
  labels:
    app: tech-challenge-app
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  SERVER_ADDRESS: "0.0.0.0"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/techchallenge"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_PROFILES_ACTIVE: "default"